[NEAT]
fitness_criterion     = max
fitness_threshold     = 10000000
pop_size              = 100
reset_on_extinction   = 1

[DefaultGenome]
num_inputs              = 3
num_hidden              = 4
num_outputs             = 2
feed_forward            = True
compatibility_disjoint_coefficient    = 1.0
compatibility_weight_coefficient      = 0.6
conn_add_prob           = 0.2
conn_delete_prob        = 0.2
node_add_prob           = 0.2
node_delete_prob        = 0.2
activation_default      = relu
activation_options      = relu
activation_mutate_rate  = 0.0
aggregation_default     = sum
aggregation_options     = sum
aggregation_mutate_rate = 0.0
bias_init_mean          = 0.0
bias_init_stdev         = 1.0
bias_init_type          = gaussian
bias_replace_rate       = 0.1
bias_mutate_rate        = 0.1
bias_mutate_power       = 1.0
bias_max_value          = 100.0
bias_min_value          = -100.0
response_init_mean      = 1.0
response_init_stdev     = 0.0
response_replace_rate   = 0.0
response_mutate_rate    = 0.0
response_mutate_power   = 0.0
response_max_value      = 100.0
response_min_value      = -100.0

weight_init_type        = gaussian
weight_max_value        = 100
weight_min_value        = -100
weight_init_mean        = 0.0
weight_init_stdev       = 1.0
weight_mutate_rate      = 0.1
weight_replace_rate     = 0.1
weight_mutate_power     = 1.0
enabled_default         = True
enabled_mutate_rate     = 0.1

[DefaultSpeciesSet]
compatibility_threshold = 3.0

[DefaultStagnation]
species_fitness_func = max
max_stagnation  = 20
species_elitism = 5

[DefaultReproduction]
elitism            = 10
survival_threshold = 0.2
